# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6634abdbcde3e56459f143daa6dd4c34ba2059ab60fd4ad185153e300e1a23ca3667fb614275021c7cbc2d9487caac1ac263c448346b2708a83c4492ed265d1

test:
  secret_key_base: 233ffbf4aece12d887c605bbd0c1d8733005339700275e0d9b92c193e165735324e789d68911c6167246c179888c8a347c103ff065ffefb4c227a7dc68ebda88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
